import { DogBreed } from '../types/calculator';

export const DOG_BREEDS: DogBreed[] = [
  { name: 'Akita', size: 'large', weightRange: { min: 32, max: 45 } },
  { name: 'Alaskan Malamute', size: 'large', weightRange: { min: 35, max: 43 } },
  { name: 'Australian Cattle Dog', size: 'medium', weightRange: { min: 15, max: 22 } },
  { name: 'Australian Shepherd', size: 'medium', weightRange: { min: 18, max: 25 } },
  { name: 'Basenji', size: 'small', weightRange: { min: 9, max: 11 } },
  { name: 'Basset Hound', size: 'medium', weightRange: { min: 20, max: 29 } },
  { name: 'Beagle', size: 'small', weightRange: { min: 9, max: 11 } },
  { name: 'Belgian Malinois', size: 'large', weightRange: { min: 25, max: 30 } },
  { name: 'Bernese Mountain Dog', size: 'giant', weightRange: { min: 40, max: 55 } },
  { name: 'Border Collie', size: 'medium', weightRange: { min: 14, max: 20 } },
  { name: 'Boxer', size: 'large', weightRange: { min: 25, max: 32 } },
  { name: 'Bulldog', size: 'medium', weightRange: { min: 18, max: 23 } },
  { name: 'Bullmastiff', size: 'giant', weightRange: { min: 45, max: 60 } },
  { name: 'Cavalier King Charles Spaniel', size: 'small', weightRange: { min: 5, max: 8 } },
  { name: 'Chihuahua', size: 'toy', weightRange: { min: 1.5, max: 3 } },
  { name: 'Cocker Spaniel', size: 'medium', weightRange: { min: 11, max: 14 } },
  { name: 'Dachshund', size: 'small', weightRange: { min: 7, max: 15 } },
  { name: 'Dalmatian', size: 'medium', weightRange: { min: 20, max: 27 } },
  { name: 'Doberman Pinscher', size: 'large', weightRange: { min: 30, max: 40 } },
  { name: 'French Bulldog', size: 'small', weightRange: { min: 8, max: 14 } },
  { name: 'German Shepherd', size: 'large', weightRange: { min: 30, max: 40 } },
  { name: 'Golden Retriever', size: 'large', weightRange: { min: 25, max: 34 } },
  { name: 'Great Dane', size: 'giant', weightRange: { min: 50, max: 90 } },
  { name: 'Irish Wolfhound', size: 'giant', weightRange: { min: 54, max: 70 } },
  { name: 'Jack Russell Terrier', size: 'small', weightRange: { min: 6, max: 8 } },
  { name: 'Labrador Retriever', size: 'large', weightRange: { min: 25, max: 36 } },
  { name: 'Maltese', size: 'toy', weightRange: { min: 3, max: 4 } },
  { name: 'Mastiff', size: 'giant', weightRange: { min: 55, max: 100 } },
  { name: 'Newfoundland', size: 'giant', weightRange: { min: 60, max: 70 } },
  { name: 'Pomeranian', size: 'toy', weightRange: { min: 1.9, max: 3.5 } },
  { name: 'Poodle (Miniature)', size: 'small', weightRange: { min: 7, max: 9 } },
  { name: 'Poodle (Standard)', size: 'large', weightRange: { min: 20, max: 32 } },
  { name: 'Poodle (Toy)', size: 'toy', weightRange: { min: 2, max: 3 } },
  { name: 'Pug', size: 'small', weightRange: { min: 6, max: 8 } },
  { name: 'Rottweiler', size: 'large', weightRange: { min: 35, max: 50 } },
  { name: 'Saint Bernard', size: 'giant', weightRange: { min: 65, max: 120 } },
  { name: 'Samoyed', size: 'large', weightRange: { min: 20, max: 30 } },
  { name: 'Siberian Husky', size: 'medium', weightRange: { min: 20, max: 27 } },
  { name: 'Shih Tzu', size: 'toy', weightRange: { min: 4, max: 7 } },
  { name: 'Yorkshire Terrier', size: 'toy', weightRange: { min: 1.8, max: 3.2 } },

  // Mixed Breed Categories
  { name: 'Mixed Breed (Small)', size: 'small', weightRange: { min: 5, max: 10 } },
  { name: 'Mixed Breed (Medium)', size: 'medium', weightRange: { min: 10, max: 25 } },
  { name: 'Mixed Breed (Large)', size: 'large', weightRange: { min: 25, max: 40 } },
  { name: 'Mixed Breed (Giant)', size: 'giant', weightRange: { min: 40, max: 80 } }
];

